Online_course_Python_Udemy = ("https://www.udemy.com/course/100-days-of-code",
    "https://www.udemy.com/course/complete-python-bootcamp/",
    "https://www.udemy.com/course/complete-python-developer-zero-to-mastery/",
    "https://www.udemy.com/course/the-modern-python3-bootcamp/",
    "https://www.udemy.com/course/python3-fundamentals/",
    "https://www.udemy.com/course/total-python/",
    "https://www.udemy.com/course/python-core-and-advanced/",
    "https://www.udemy.com/course/python-for-absolute-beginners-u/",
    "https://www.udemy.com/course/python-the-complete-python-developer-course/",
    "https://www.udemy.com/course/complete-python-developer-zero-to-master")
Online_course_Python_Coursera = ("https://www.coursera.org/specializations/python-3-programming",
    "https://www.coursera.org/learn/python-crash-course",
    "https://www.coursera.org/learn/python-for-applied-data-science-ai",
    "https://www.coursera.org/learn/get-started-with-python",
    "https://www.coursera.org/learn/python-programming-intro",
    "https://www.coursera.org/specializations/python-3-programming",
    "https://www.coursera.org/learn/python-crash-course",
    "https://www.coursera.org/learn/python-for-applied-data-science-ai",
    "https://www.coursera.org/learn/get-started-with-python",
    "https://www.coursera.org/learn/python-programming-intro")

Online_course_Java_Udemy = ("https://www.udemy.com/course/java-the-complete-java-developer-course/",
    "https://www.udemy.com/course/java-se-programming/",
    "https://www.udemy.com/course/java-programming-tutorial-for-beginners/",
    "https://www.udemy.com/course/the-complete-java-development-bootcamp/",
    "https://www.udemy.com/course/full-stack-java-developer-java/",
    "https://www.udemy.com/course/java-development-for-beginners-learnit/",
    "https://www.udemy.com/course/java-programming-complete-beginner-to-advanced/",
    "https://www.udemy.com/course/master-practical-java-development/",
    "https://www.udemy.com/course/practical-java-course/",
    "https://www.udemy.com/course/java-11-complete-beginners/")
Online_course_Java_Coursera = ("https://www.coursera.org/specializations/javascript-beginner",
    "https://www.coursera.org/learn/html-css-javascript-for-web-developers",
    "https://www.coursera.org/learn/programming-with-javascript",
    "https://www.coursera.org/learn/javascript-basics",
    "https://www.coursera.org/learn/learn-javascript",
    "https://www.coursera.org/specializations/javascript-beginner",
    "https://www.coursera.org/learn/html-css-javascript-for-web-developers",
    "https://www.coursera.org/learn/programming-with-javascript",
    "https://www.coursera.org/learn/javascript-basics",
    "https://www.coursera.org/learn/learn-javascript")

Online_course_Javascript_Udemy = ("https://www.udemy.com/course/the-complete-javascript-course/",
    "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    "https://www.udemy.com/course/javascript-the-complete-guide-2020-beginner-advanced/",
    "https://www.udemy.com/course/advanced-javascript-concepts/",
    "https://www.udemy.com/course/javascript-basics-for-beginners/",
    "https://www.udemy.com/course/javascript-beginners-complete-tutorial/",
    "https://www.udemy.com/course/modern-javascript-from-the-beginning/",
    "https://www.udemy.com/course/javascript-tutorial-for-beginners-w/",
    "https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/",
    "https://www.udemy.com/course/the-complete-web-developer-zero-to-mastery/"
)
Online_course_Javascript_Coursera = ("https://www.coursera.org/specializations/javascript-beginner",
    "https://www.coursera.org/learn/html-css-javascript-for-web-developers",
    "https://www.coursera.org/learn/programming-with-javascript",
    "https://www.coursera.org/learn/javascript-basics",
    "https://www.coursera.org/learn/learn-javascript",
    "https://www.coursera.org/specializations/javascript-beginner",
    "https://www.coursera.org/learn/html-css-javascript-for-web-developers",
    "https://www.coursera.org/learn/programming-with-javascript",
    "https://www.coursera.org/learn/javascript-basics",
    "https://www.coursera.org/learn/learn-javascript")

Online_course_C_Udemy = ( "https://www.udemy.com/course/the-complete-web-developer-zero-to-mastery/",
    "https://www.udemy.com/course/beginning-c-plus-plus-programming/",
    "https://www.udemy.com/course/cpp-deep-dive/",
    "https://www.udemy.com/course/the-modern-cpp-20-masterclass/",
    "https://www.udemy.com/course/beg-modern-cpp/",
    "https://www.udemy.com/course/learn-c-and-c-beginner-to-advance/",
    "https://www.udemy.com/course/c-coding-learn-c-programming-with-examples-in-one-day/",
    "https://www.udemy.com/course/the-complete-cpp-developer-course/",
    "https://www.udemy.com/course/quick-start-to-modern-c-for-programmers/",
    "https://www.udemy.com/course/cplusplus-programming-step-by-step/")
Online_course_C_Coursera = ("https://www.coursera.org/specializations/coding-for-everyone",
    "https://www.coursera.org/specializations/c-programming",
    "https://www.coursera.org/specializations/hands-on-cpp",
    "https://www.coursera.org/learn/programming-languages-part-c",
    "https://www.coursera.org/specializations/cplusplusunrealgamedevelopment",
    "https://www.coursera.org/specializations/coding-for-everyone",
    "https://www.coursera.org/specializations/c-programming",
    "https://www.coursera.org/specializations/hands-on-cpp",
    "https://www.coursera.org/learn/programming-languages-part-c",
    "https://www.coursera.org/specializations/cplusplusunrealgamedevelopment")


Youtube_video_python = ("https://www.youtube.com/watch?v=_uQrJ0TkZlc&pp=ygUHUHl0aG9uIA%3D%3D",
    "https://www.youtube.com/watch?v=7wnove7K-ZQ&list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg",
    "https://www.youtube.com/watch?v=VchuKL44s6E&pp=ygUHUHl0aG9uIA%3D%3D",
    "https://www.youtube.com/watch?v=rfscVS0vtbw&pp=ygUOUHl0aG9uICBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=6i3EGqOBRiU&list=PLdo5W4Nhv31bZSiqiOL5ta39vSnBxpOPT",
    "https://www.youtube.com/watch?v=XKHEtdqhLK8&pp=ygUOUHl0aG9uICBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=mRMmlo_Uqcs&list=PLIhvC56v63ILPDA2DQBv0IKzqsWTZxCkp",
    "https://www.youtube.com/watch?v=nLRL_NcnK-4&pp=ygUOUHl0aG9uICBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=sxTmJE4k0ho&pp=ygUOUHl0aG9uICBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=fqF9M92jzUo&t=4s&pp=ygUOUHl0aG9uICBjb3Vyc2U%3D")

Youtube_video_Java = ("https://www.youtube.com/watch?v=yRpLlJmRo2w&list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
    "https://www.youtube.com/watch?v=eIrMbAQSU34&pp=ygUMSmF2YSAgY291cnNl",
    "https://www.youtube.com/watch?v=BGTx91t8q50&pp=ygUMSmF2YSAgY291cnNl",
    "https://www.youtube.com/watch?v=VHbSopMyc4M&list=PLBlnK6fEyqRjKA_NuK9mHmlk0dZzuP1P5",
    "https://www.youtube.com/watch?v=wdkP056q0Nc&pp=ygUMSmF2YSAgY291cnNl",
    "https://www.youtube.com/watch?v=grEKMHGYyns&pp=ygUMSmF2YSAgY291cnNl",
    "https://www.youtube.com/watch?v=RJ733wzbNoA&list=PLxgZQoSe9cg00xyG5gzb5BMkOClkch7Gr",
    "https://www.youtube.com/watch?v=j9VNCI9Xo80&pp=ygUMSmF2YSAgY291cnNl",
    "https://www.youtube.com/watch?v=drQK8ciCAjY&pp=ygUMSmF2YSAgY291cnNl",
    "https://www.youtube.com/watch?v=UmnCZ7-9yDY&t=433s&pp=ygUMSmF2YSAgY291cnNl")

Youtube_video_Javascript =(
    "https://www.youtube.com/watch?v=ER9SspLe4Hg&list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR",
    "https://www.youtube.com/watch?v=W6NZfCO5SIk&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=PkZNo7MFNFg&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=SBmSRK3feww&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=jS4aFq5-91M&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=Qqx_wzMmFeA&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=lI1ae4REbFM&t=76s&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=acUEBly28UU&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=IC5vBKc21X8&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D",
    "https://www.youtube.com/watch?v=8dWL3wF_OMw&pp=ygURamF2YXNjcmlwdCBjb3Vyc2U%3D"
)

Youtube_video_C = ("https://www.youtube.com/watch?v=z9bZufPHFLU&list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ",
    "https://www.youtube.com/watch?v=vLnPwxZdW4Y&pp=ygUPYysrIGZ1bGwgY291cnNl",
    "https://www.youtube.com/watch?v=8jLOx1hD3_o&pp=ygUPYysrIGZ1bGwgY291cnNl",
    "https://www.youtube.com/watch?v=ZzaPdXTrSb8&pp=ygUPYysrIGZ1bGwgY291cnNl",
    "https://www.youtube.com/watch?v=-TkoO8Z07hI&pp=ygUPYysrIGZ1bGwgY291cnNl",
    "https://www.youtube.com/watch?v=oOmbSpOzvYg&list=PLdo5W4Nhv31YU5Wx1dopka58teWP9aCee",
    "https://www.youtube.com/watch?v=WQoB2z67hvY&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA",
    "https://www.youtube.com/watch?v=iOfUlcUy0as&pp=ygUPYysrIGZ1bGwgY291cnNl",
    "https://www.youtube.com/watch?v=FpfHmAkRVK4&pp=ygUPYysrIGZ1bGwgY291cnNl",
    "https://www.youtube.com/watch?v=bL-o2xBENY0&list=PLxgZQoSe9cg0df_GxVjz3DD_Gck5tMXAd")
